### ISSUE TITLE
使用 enwaiax/x-ui:alpha 版本时，如何使用中文语言版本？

### ISSUE THREAD

**Issue by TaoRone** [enwaiax/x-ui#10]
先谢谢大佬制作的docker镜像！十分好用！

使用[FranzKafkaYu/x-ui](https://github.com/FranzKafkaYu/x-ui)版本，仅需要讲上述镜像修改为 enwaiax/x-ui:alpha…………

针对这一条，请问如何修改docker cli 使其成中文版？

**Comment by enwaiax** [comment]
镜像换成 `enwaiax/x-ui:alpha-zh`

**Comment by TaoRone** [comment]
> 镜像换成 `enwaiax/x-ui:alpha-zh`

十分感谢！！
