### ISSUE TITLE
mac surge 连接不上

### ISSUE THREAD

**Issue by 1stzer** [enwaiax/x-ui#11]
用最新的 image 搭建的 vmess ws 协议服务端，mac surge 连接不上，不过其它客户端能连接。
退回到 image id：e6e8975d8c1f 这个版本后，mac surge 可以连接，其它客户端也正常。
不知道最新版本改了啥？
docker ps 后，以前的 command 是 "./x-ui"，现在的 command 的是 "x-ui"。有影响吗？

**Comment by enwaiax** [comment]
1. official版本不做修改，只拉去最新镜像打包
2. 没有影响，只是把x-ui的执行路径加入到全局环境变量了
