### ISSUE TITLE
使用ipv6连接时vmess协议的alterid

### ISSUE THREAD

**Issue by kaiwenyao** [enwaiax/x-ui#12]
使用`docker`部署`x-ui`, 配置vmess+ws节点, 其中`alterid = 64`. 导入`open clash`后手动修改连接地址为**ipv6**, 发现无法连通. 最初以为是自己本地ipv6配置问题.
随后改为使用**一键脚本**部署`x-ui`, 同样手动修改连接地址为**ipv6**. 可以连通.

用安卓端客户端`sager net`导入`docker`部署的vmess+ws节点, 可用.
从`sager net`导出节点, 再导入`open clash`, 发现不包含**alterid**信息.

随后手动修改从`x-ui`导出的节点信息`alterid = 64` => `alterid = 0`, 可以连通.

(如果之前有出过相关issue/官方教程就当我没说, 我刚刚才发现~

**Comment by enwaiax** [comment]
第一个问题， 如果想要使用ipv6地址，需要对docker启用ipv6。推荐的做法是使用nginx做前置代理，docker x-ui只管接受nginx转发过来的流量

第二个问题， 不清楚原因，可能跟sager net本身到处的格式有关，建议使用从x-ui dashboard导出的链接，或者直接扫描二维码

**Comment by kaiwenyao** [comment]
其实我的意思是`docker`搭建`x-ui`后部署vmess的alterid在使用`ipv6`连接的情况下需要把客户端的`alterid`**修改为0**才能连通, 即使服务端设置的是`64`

使用`sager net`导入节点是为了测试连通性, 因为我不太熟悉`open clash`, 怕因此导致误判. 不过我发现`sager net`根本就没有给vmess配置`alterid`的选项, 所以他才能连通. 于是我把`open clash`节点配置的`alterid`也修改为0, 同样可以连通了.

全程没有修改过`docker`关于`ipv6`的设置, 不清楚修改后是否可以实现服务端和客户端统一`alterid`也可连通.

**Comment by enwaiax** [comment]
哦哦，多谢反馈
