### ISSUE TITLE
可以和nginx proxy manager共存吗。

### ISSUE THREAD

**Issue by liang-x-j** [enwaiax/x-ui#13]
作者好，我尝试了在安装nginx proxy manager后安装作者的容器，但是总是启动不成功，希望作者指导一下，感谢不尽

**Comment by enwaiax** [comment]
有什么报错吗，贴下log

**Comment by kaiwenyao** [comment]
我测试了可以共存, 没有任何问题的. 也是先安装npm然后安装x-ui

**Comment by enwaiax** [comment]
是的，一般来说没有任何冲突。NPM挺吃资源的，所以没有写使用NPM的教程
