### ISSUE TITLE
x-ui panel with docker

### ISSUE THREAD

**Issue by ali-hosini** [enwaiax/x-ui#14]
Hello, I have installed the FranzKafkaYu panel and I have a question, how can I access the x-ui panel through Docker? I tested everything I thought.
In the end, when I executed Docker and entered the bash environment and gave the x-ui command, this happened:
![image](https://user-images.githubusercontent.com/89318654/232278278-0e2c553e-1c98-462c-a9de-ceee42f9df5b.png)
please help me ,thanks

**Comment by enwaiax** [comment]
There is no such thing as x-ui panel. In FranzKafkaYu Panel, the x-ui panel is a shell script that allows you to control the x-ui service, such as install, uninstall and update. In docker, it's the x-ui binary. You do not need to worry about how to interact with the x-ui service.
But you can still use `x-ui help` to use the subcommand supported by the x-ui binary

**Comment by ali-hosini** [comment]
How about the other panels? Isn't there a panel for them in the Docker environment?
And what do you suggest to install two panels in one server?

**Comment by enwaiax** [comment]
No, there is no such panel because it's not needed at all.
It's using host network so if you want to install two panels you need to change the docker-compose.yaml file like using bridge network but you need export the port you want to use to run the xray or v2ray by your self.

**Comment by ali-hosini** [comment]
i install with this command 
mkdir x-ui1 && cd x-ui1
docker run -itd --network=host\
    -v $PWD/db1/:/etc/x-ui1/ \
    -v $PWD/cert1/:/root/cert1/ \
    --name x-ui1 --restart=unless-stopped \
    enwaiax/x-ui:alpha

and i add a number for every dir and name 
can you tell me What else should I change?

**Comment by enwaiax** [comment]
Try to learn something about docker network model. What is host network and what is bridge network.

It makes no difference how many panel you install.

**Comment by ali-hosini** [comment]
thanks for reply ,
have nice night
