### ISSUE TITLE
镜像build_image/Dockerfile.alpha-zh重新编译之后日志一直输出警告

### ISSUE THREAD

**Issue by wxywizard** [enwaiax/x-ui#16]
你好我本地重新build了一下这个镜像build_image/Dockerfile.alpha-zh之后，启动一直提示这个警告，请问是什么原因？
<img width="1318" alt="CleanShot 2023-05-27 at 11 50 06@2x" src="https://github.com/Chasing66/x-ui/assets/28422371/d2fb8967-e762-4190-a9a6-924c713ef83a">

**Comment by enwaiax** [comment]
应该是原项目的问题，我试了一下，你第一次登录进去后，重新设置了path以后就不会报错了
