### ISSUE TITLE
How to enable TLS?

### ISSUE THREAD

**Issue by reg3xp** [enwaiax/x-ui#22]
I have placed cert.pem and private.pem for the subdomain inside container /root/cert/
and added the path in panel like /root/cert/private.pem and /root/cert/cert.pem
but TLS doesn't work.

**Comment by enwaiax** [comment]
I would suggest you use Nginx to reverse it
https://github.com/Chasing66/x-ui#how-to-enable-ssl-to-your-x-ui-panel
