### ISSUE TITLE
新版3x-ui启动不了

### ISSUE THREAD

**Issue by waipan** [enwaiax/x-ui#39]
你好，我是用群辉的DOCKER用家， 之前是用x-ui ALPHA版本，现在想改换3x-ui...
我安装后发现进不了端口54321 /2053 设置3x-ui，附图是直接run x-ui的结果，
请问是不是我那里出了问题？

![image](https://github.com/user-attachments/assets/9c9d168b-0add-4ff6-a5cb-51dff13744b0)

**Comment by enwaiax** [comment]
容器启动后会自动运行3x-ui进程，占用2053端口，无需手动启动

**Comment by waipan** [comment]
可以了，谢谢！
